chore: Fix ShellCheck warnings
* Introduced a new template for domains that can be blocked based on time.
* Updated init scripts to use /usr/bin/env bash for better portability.
* Enhanced various init scripts with consistent formatting and improved variable handling.
* Added ntpdate service for time synchronization.

diff --git a/root/TEMPLATEs/init/S57nfs-kernel-server.tmpl b/root/TEMPLATEs/init/S57nfs-kernel-server.tmpl
--- a/root/TEMPLATEs/init/S57nfs-kernel-server.tmpl
+++ b/root/TEMPLATEs/init/S57nfs-kernel-server.tmpl
@@ -1,4 +1,5 @@
-#!/opt/bin/bash
+#!/usr/bin/env bash
+# shellcheck disable=SC1091
 
 PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
 ENABLED=no
@@ -6,80 +7,80 @@ PROCS=nfs-kernel-server
 ARGS=""
 PREARGS=""
 DESC="NFS Server"
-export ENABLED PROCS ARGS PREARGS DESC
+export ENABLED PROCS ARGS PREARGS DESC PATH
 
 # shellcheck source=root/TEMPLATEs/init/rc.func.tmpl
-[ -n "$LOOP" ] && . /opt/etc/init.d/rc.func
+[[ -n ${LOOP} ]] && . /opt/etc/init.d/rc.func
 
 PATH=/opt/bin:/opt/sbin:/sbin:/bin:/usr/sbin:/usr/bin
 
-if [ -z "$(pidof rpcbind)" ]; then
-	#echo 'Error: portmap not started'
-	exit 1
+if [[ -z $(pidof rpcbind) ]]; then
+    #echo 'Error: portmap not started'
+    exit 1
 fi
 
 start() {
-	echo 'Starting NFS server'
-	modprobe nfsd
-	mkdir -p /opt/var/lib/nfs/sm
-	mkdir -p /opt/var/lib/nfs/sm.bak
-	mkdir -p /opt/var/lib/nfs/rpc_pipefs
-	echo -n >/opt/var/lib/nfs/etab
-	echo -n >/opt/var/lib/nfs/rmtab
-	echo -n >/opt/var/lib/nfs/xtab
-	mount -t rpc_pipefs rpc_pipefs /opt/var/lib/nfs/rpc_pipefs
-	mount -t nfsd nfsd /proc/fs/nfsd
-	echo 65536 >/proc/fs/nfsd/max_block_size
-	exportfs -ra
-	rpc.nfsd --no-nfs-version 4 --no-tcp 1
-	rpc.mountd --no-nfs-version 4 --no-tcp
+    echo 'Starting NFS server'
+    modprobe nfsd
+    mkdir -p /opt/var/lib/nfs/sm
+    mkdir -p /opt/var/lib/nfs/sm.bak
+    mkdir -p /opt/var/lib/nfs/rpc_pipefs
+    echo -n >/opt/var/lib/nfs/etab
+    echo -n >/opt/var/lib/nfs/rmtab
+    echo -n >/opt/var/lib/nfs/xtab
+    mount -t rpc_pipefs rpc_pipefs /opt/var/lib/nfs/rpc_pipefs
+    mount -t nfsd nfsd /proc/fs/nfsd
+    echo 65536 >/proc/fs/nfsd/max_block_size
+    exportfs -ra
+    rpc.nfsd --no-nfs-version 4 --no-tcp 1
+    rpc.mountd --no-nfs-version 4 --no-tcp
 }
 
 stop() {
-	echo 'Stopping NFS server'
-	killall -q rpc.mountd >/dev/null
-	killall -q -2 nfsd >/dev/null
-	exportfs -ua
-	umount /proc/fs/nfsd 2>/dev/null
-	umount /opt/var/lib/nfs/rpc_pipefs 2>/dev/null
-	rm -f /opt/var/lib/nfs/etab
+    echo 'Stopping NFS server'
+    killall -q rpc.mountd >/dev/null
+    killall -q -2 nfsd >/dev/null
+    exportfs -ua
+    umount /proc/fs/nfsd 2>/dev/null
+    umount /opt/var/lib/nfs/rpc_pipefs 2>/dev/null
+    rm -f /opt/var/lib/nfs/etab
 }
 
 status() {
-	if [ -n "$(pidof nfsd)" ] && [ -n "$(pidof rpc.mountd)" ]; then
-		echo 'NFS server is running'
-	else
-		echo 'NFS server is stopped'
-	fi
+    if [[ -n $(pidof nfsd) && -n $(pidof rpc.mountd) ]]; then
+        echo 'NFS server is running'
+    else
+        echo 'NFS server is stopped'
+    fi
 }
 
 reload() {
-	echo 'Reloading /opt/etc/exports'
-	exportfs -r
+    echo 'Reloading /opt/etc/exports'
+    exportfs -r
 }
 
 case "$1" in
-start)
-	start
-	;;
-stop)
-	stop
-	;;
-restart)
-	stop
-	sleep 2
-	start
-	;;
-status)
-	status
-	;;
-reload)
-	reload
-	;;
-*)
-	echo "Usage: $0 (start|stop|restart|reload|status)"
-	exit 1
-	;;
+    start)
+        start
+        ;;
+    stop)
+        stop
+        ;;
+    restart)
+        stop
+        sleep 2
+        start
+        ;;
+    status)
+        status
+        ;;
+    reload)
+        reload
+        ;;
+    *)
+        echo "Usage: $0 (start|stop|restart|reload|status)"
+        exit 1
+        ;;
 esac
 
 exit 0
diff --git a/root/TEMPLATEs/init/rc.func.tmpl b/root/TEMPLATEs/init/rc.func.tmpl
--- a/root/TEMPLATEs/init/rc.func.tmpl
+++ b/root/TEMPLATEs/init/rc.func.tmpl
@@ -1,4 +1,4 @@
-#!/opt/bin/bash
+#!/usr/bin/env bash
 
 ACTION="$1"
 CALLER="$2"
@@ -12,115 +12,130 @@ ansi_std="\033[m"
 start() {
     unset LOOP
 
-    {
-        [ "$CRITICAL" != "yes" ]
-        [ "$CALLER" = "cron" ]
-    } && return 7
-    [ "$ENABLED" != "yes" ] && return 8
-    echo -e -n "$ansi_white Starting $DESC... $ansi_std"
-    if [ -n "$(pidof "$PROC")" ]; then
-        echo -e "$ansi_yellow already running. $ansi_std"
+    [[ ${CRITICAL} != "yes" && ${CALLER} = "cron" ]] && return 7
+    [[ ${ENABLED} != "yes" ]] && return 8
+    echo -e -n "${ansi_white} Starting ${DESC}... ${ansi_std}"
+    if [[ -n $(pidof "${PROC}") ]]; then
+        echo -e "${ansi_yellow} already running. ${ansi_std}"
         return 0
     fi
 
-    case "$PROC" in
+    case "${PROC}" in
         'dnscrypt-proxy')
             /opt/etc/init.d/S09dnscrypt-proxy2 restart
             ;;
         'vpnclient1' | 'vpnclient2' | 'vpnclient3' | 'vpnserver1' | 'vpnserver2' | 'vpnserver3')
-            service "$PROC" restart >/dev/null
+            service "${PROC}" restart >/dev/null
             ;;
         'dnsmasq' | 'cstats' | 'rstats' | 'smbd')
-            service "$PROC" restart >/dev/null
+            service "${PROC}" restart >/dev/null
             ;;
         *)
-            $PRECMD >/dev/null 2>&1
-            eval "$PREARGS $PROC $ARGS"
+            ${PRECMD} >/dev/null 2>&1
+            eval "${PREARGS} ${PROC} ${ARGS}"
+            local RES=$?
             ;;
     esac
 
-    COUNTER=0
-    LIMIT=20
+    case "${PROC}" in
+        'ntpdate') ;;
+        *)
+            COUNTER=0
+            LIMIT=20
+            while [[ -z $(pidof "${PROC}") && ${COUNTER} -le "${LIMIT}" ]]; do
+                sleep 1
+                COUNTER=$((COUNTER + 1))
+            done
+            ;;
+    esac
+    ${POSTCMD} >/dev/null 2>&1
 
-    while [ -z "$(pidof "$PROC")" ] && [ "$COUNTER" -le "$LIMIT" ]; do
-        sleep 1
-        COUNTER=$((COUNTER + 1))
-    done
-    $POSTCMD >/dev/null 2>&1
-
-    if [ -z "$(pidof "$PROC")" ]; then
-        echo -e "$ansi_red failed. $ansi_std"
-        logger "Failed to start $DESC from $CALLER."
-        return 255
-    else
-        echo -e "$ansi_green done. $ansi_std"
-        logger "Started $DESC from $CALLER."
-        return 0
-    fi
+    case "${PROC}" in
+        'ntpdate')
+            if [[ ${RES} -ne 0 ]]; then
+                echo -e "${ansi_red} failed. ${ansi_std}"
+                return 255
+            else
+                echo -e "${ansi_green} done. ${ansi_std}"
+                return 0
+            fi
+            ;;
+        *)
+            if [[ -z $(pidof "${PROC}") ]]; then
+                echo -e "${ansi_red} failed. ${ansi_std}"
+                logger "Failed to start ${DESC} from ${CALLER}."
+                return 255
+            else
+                echo -e "${ansi_green} done. ${ansi_std}"
+                logger "Started ${DESC} from ${CALLER}."
+                return 0
+            fi
+            ;;
+    esac
 }
 
 stop() {
     unset LOOP
 
-    case "$ACTION" in
+    case "${ACTION}" in
         stop | restart)
-            echo -e -n "$ansi_white Shutting down $PROC... $ansi_std"
+            echo -e -n "${ansi_white} Shutting down ${PROC}... ${ansi_std}"
 
-            case "$PROC" in
+            case "${PROC}" in
                 'dnscrypt-proxy')
-                    /opt/etc/init.d/S09dnscrypt-proxy2 "$ACTION"
+                    /opt/etc/init.d/S09dnscrypt-proxy2 "${ACTION}"
                     ;;
                 'vpnclient1' | 'vpnclient2' | 'vpnclient3' | 'vpnserver1' | 'vpnserver2' | 'vpnserver3')
-                    service "$PROC" "$ACTION" >/dev/null
+                    service "${PROC}" "${ACTION}" >/dev/null
                     ;;
                 'dnsmasq' | 'cstats' | 'rstats' | 'smbd')
-                    service "$PROC" "$ACTION" >/dev/null
+                    service "${PROC}" "${ACTION}" >/dev/null
                     ;;
-                *) killall "$PROC" >/dev/null ;;
+                *) killall "${PROC}" >/dev/null ;;
             esac
 
             COUNTER=0
             LIMIT=10
-            while [ -n "$(pidof "$PROC")" ] && [ "$COUNTER" -le "$LIMIT" ]; do
+            while [[ -n $(pidof "${PROC}") && ${COUNTER} -le "${LIMIT}" ]]; do
                 sleep 1
                 COUNTER=$((COUNTER + 1))
             done
             ;;
         kill)
-            echo -e -n "$ansi_white Killing $PROC... $ansi_std"
-            killall -9 "$PROC" >/dev/null
+            echo -e -n "${ansi_white} Killing ${PROC}... ${ansi_std}"
+            killall -9 "${PROC}" >/dev/null
             ;;
     esac
 
-    if [ -n "$(pidof "$PROC")" ]; then
-        echo -e "$ansi_red failed. $ansi_std"
+    if [[ -n $(pidof "${PROC}") ]]; then
+        echo -e "${ansi_red} failed. ${ansi_std}"
         return 255
     else
-        echo -e "$ansi_green done. $ansi_std"
+        echo -e "${ansi_green} done. ${ansi_std}"
         return 0
     fi
 }
 
 check() {
-    echo -e -n "$ansi_white Checking $DESC... "
-    if [ -n "$(pidof "$PROC")" ]; then
-        echo -e "$ansi_green alive. $ansi_std"
+    echo -e -n "${ansi_white} Checking ${DESC}... ${ansi_std}"
+    if [[ -n $(pidof "${PROC}") ]]; then
+        echo -e "${ansi_green} alive. ${ansi_std}"
         return 0
     else
-        echo -e "$ansi_red dead. $ansi_std"
+        echo -e "${ansi_red} dead. ${ansi_std}"
         return 1
     fi
 }
 
 reconfigure() {
     SIGNAL=SIGHUP
-    echo -e "$ansi_white Sending $SIGNAL to $PROC... $ansi_std"
-    killall -$SIGNAL "$PROC" >/dev/null
+    echo -e "${ansi_white} Sending ${SIGNAL} to ${PROC}... ${ansi_std}"
+    killall -${SIGNAL} "${PROC}" >/dev/null
 }
 
 export PROCS
-for PROC in $PROCS; do
-    case "$ACTION" in
+for PROC in ${PROCS}; do
+    case "${ACTION}" in
         start)
             start
             ;;
@@ -138,7 +153,7 @@ for PROC in $PROCS; do
             reconfigure
             ;;
         *)
-            echo -e "$ansi_white Usage: $0 (start|stop|restart|check|kill|reconfigure)$ansi_std"
+            echo -e "${ansi_white} Usage: $0 (start|stop|restart|check|kill|reconfigure)${ansi_std}"
             exit 1
             ;;
     esac
